### PR TITLE
open-soure project list for MT3620

### PR DESCRIPTION
**Pull request by dhe-engineer**
# Description

Added a list of 3rd party open-source projects supporting external hardware on the Azure Sphere MT3620 platform

## Type of change

Please delete options that are not relevant.

- New content

# Checklist:

- [ ] My content has a file named README.md, which is based on the appropriate readme [template](https://github.com/Azure/azure-sphere-gallery/tree/main/Templates)
- [x] I have performed a self-review of my own contribution
- [ ] I have provided comments where appropriate
- [x] I have updated the repository's [README.md](https://github.com/Azure/azure-sphere-gallery/blob/main/README.md) to index this project
- [x] I have added/updated license(s) for this project as appropriate
- [x] I have permission to publish this content (in case the content was collaborative)
- [x] I have verified that my content does not contain sensitive information (PII, Microsoft PI, etc.) and is safe to open source

### CODE REVIEW

**Comment by kenwoodberry** [comment]
@dhe-engineer , I think we should change the name of the folder from 3rdPartyOpenSourceProjects to something that reflects that these projects are about supporting external perhipherals.  So how about OpenSourceProjectsSupportingExternalPeripherals ?Thanks.

**Comment by dhe-engineer** [comment]
> @dhe-engineer , I think we should change the name of the folder from 3rdPartyOpenSourceProjects to something that reflects that these projects are about supporting external perhipherals. So how about OpenSourceProjectsSupportingExternalPeripherals ?Thanks.


The folder name has been updated as suggested

**Review by kenwoodberry — APPROVED** [review]

**Comment by bawilless** [comment]
I would love to see this make it into the repo.  Is there a time frame for merging this list into the repo?  I would like to advertise the content to the community.

**Comment by tokenstar** [comment]
@bawilless  thanks for the prod to complete this PR! glad its useful, and we welcome updates to add more community project links.

**Pull request merged**
